from . import credit_report_mixin
from . import credit_activity_wizard
from . import credit_config
from . import credit_dashboard
from . import credit_issue_wizard
from . import credit_ledger_entry
from . import credit_outstanding_wizard
from . import credit_reason
from . import credit_reports
from . import credit_statement_wizard
from . import credit_transactions
from . import res_partner
