from . import stock_mixin
from . import stock_picking
from . import stock_receive
from . import stock_receive_charge
from . import stock_receive_pricing_wizard
from . import stock_receive_pay_wizard
from . import stock_return
from . import stock_return_history
from . import purchase_order_line
from . import product_template
from . import product_product
from . import product_label_layout
from . import stock_take
from . import account_move_line
